all: acertar_1 acertar_N acertar_1_USR1 acertar_N_USR1 mem_N direcciones_memoria
acertar_1: acertar_1.c
	gcc -g -Wall acertar_1.c -o acertar_1
acertar_N: acertar_N.c
	gcc -g -Wall acertar_N.c -o acertar_N
acertar_1_USR1: acertar_1_USR1.c
	gcc -g -Wall acertar_1_USR1.c -o acertar_1_USR1
acertar_N_USR1: acertar_N_USR1.c
	gcc -g -Wall acertar_N_USR1.c -o acertar_N_USR1
mem_N: mem_N.c
	gcc -g -Wall mem_N.c -o mem_N
direcciones_memoria: direcciones_memoria.c
	gcc -g -Wall direcciones_memoria.c -o direcciones_memoria
