all: prog_a prog_b prog_c prog_d prog_e lletra msize

prog_a: prog_a.c
	gcc prog_a.c -o prog_a

prog_b: prog_b.c
	gcc prog_b.c -o prog_b

prog_c: prog_c.c
	gcc prog_c.c -o prog_c

prog_d: prog_d.c
	gcc prog_d.c -o prog_d

prog_e: prog_e.c
	gcc prog_e.c -o prog_e

lletra: lletra.c
	gcc lletra.c -o lletra

msize: msize.c
	gcc msize.c -o msize

clean:
	rm -f *.o prog_a prog_b prog_c prog_d prog_e lletra msize
