
all: mod51 filtra1a10 maxmin

mod51: mod51.c
	gcc -Wall mod51.c -o mod51

filtra1a10: filtra1a10.c
	gcc -Wall filtra1a10.c -o filtra1a10

maxmin: maxmin.c
	gcc -Wall maxmin.c -o maxmin

clean: 
	rm mod51 filtra1a10 maxmin

