all:EscribeNumeros LeeNumeros FiltraTrozo pares

EscribeNumeros:EscribeNumeros.c
	gcc -o  EscribeNumeros EscribeNumeros.c
LeeNumeros:LeeNumeros.c
	gcc -o LeeNumeros LeeNumeros.c

FiltraTrozo:FiltraTrozo.c
	gcc -o FiltraTrozo FiltraTrozo.c
pares:pares.c
	gcc -o pares pares.c
clean:
	rm -rf EscribeNumeros LeeNumeros FiltraTrozo pares
